#!/usr/bin/env bash
#
# installs extras

# https://rvm.io
# rvm for the rubiess
curl -L https://get.rvm.io | bash -s stable --ruby

# homebrew!
# you need the code CLI tools YOU FOOL.
ruby <(curl -fsSkL raw.github.com/mxcl/homebrew/go)

# https://github.com/carlhuda/janus
# Vim Janus
curl -Lo- https://bit.ly/janus-bootstrap | bash

# https://github.com/rupa/z
# z, oh how i love you
mkdir -p ~/Development/z
curl https://raw.github.com/rupa/z/master/z.sh > ~/Development/z/z.sh
chmod +x ~/Development/z/z.sh

# https://github.com/dronir/SpotifyControl
# Spotify Controll Script
cd ~/Development
git clone git://github.com/dronir/SpotifyControl.git

# https://github.com/jeroenbegyn/VLCControl
# VLC Controll Script
cd ~/Development
git clone git://github.com/jeroenbegyn/VLCControl.git

# for the c alias (syntax highlighted cat)
sudo easy_install Pygments
